In [1]:
import torch 
shape=(2,3)
tensor = torch.rand(shape)
print(tensor.dtype)
print(tensor.device)
print(tensor.shape)

torch.float32
cpu
torch.Size([2, 3])


slicing (Indexing)

In [23]:
print(tensor)
print(tensor[:,0:3])# here 0:3 means 0,1,2 columns 
tensor = torch.ones(4, 4)

# Accessing data
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

# Modifying data in-place using slicing
tensor[:, 1] = 0 
# This sets every element in the second column (index 1) to zero
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


concatenation is adding another tensor without changing the dimension whereas 
stacking is like creating another dimension

In [37]:
x = torch.tensor([[1,2,3],[4,5,6]])
y=torch.tensor([[7,8,9],[10,11,12]])

a=torch.cat((x,y),dim=0) # concatenating along the rows
b=torch.stack((x,y),dim=2) # stacking along the columns
print(a)
print(a.shape)
print(b)
print(b.shape)
print(x.shape)
print(y.shape)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
torch.Size([4, 3])
tensor([[[ 1,  7],
         [ 2,  8],
         [ 3,  9]],

        [[ 4, 10],
         [ 5, 11],
         [ 6, 12]]])
torch.Size([2, 3, 2])
torch.Size([2, 3])
torch.Size([2, 3])


matrix multiplication is @ 
and 
element wise multiplication is *

In [ ]:
tensor2 = torch.rand(3,4)
tensor3 = torch.rand(3,4)

print(tensor@tensor2) # matrix multiplication
print(tensor2*tensor3) # elementwise multiplication

tensor([[0.6058, 0.5439, 0.5507, 0.6818],
        [0.2601, 0.3073, 0.3486, 0.4918]])
tensor([[5.2532e-01, 1.5867e-02, 2.7341e-01, 3.4091e-02],
        [2.8939e-01, 4.2025e-01, 1.1341e-01, 1.1268e-02],
        [4.1920e-04, 1.1753e-01, 9.8590e-02, 4.2642e-01]])


from numpy to torch

In [16]:
import numpy as np 

arr=np.random.rand(3,4)
ten = torch.from_numpy(arr)
print(arr)
print(ten)

[[0.79057815 0.91138141 0.47653107 0.42548509]
 [0.76274484 0.81105466 0.13438746 0.40054016]
 [0.16799007 0.6173253  0.9713871  0.11412987]]
tensor([[0.7906, 0.9114, 0.4765, 0.4255],
        [0.7627, 0.8111, 0.1344, 0.4005],
        [0.1680, 0.6173, 0.9714, 0.1141]], dtype=torch.float64)


from another tensor

torch.ones_like(x_data): Creates a tensor filled with 1s using the same shape and type as x_data.

torch.rand_like(x_data, dtype=torch.float): Creates a tensor with random values, keeping the shape but overriding the data type to a float.

In [21]:
tensor4 = torch.rand_like(ten,dtype=torch.float64)
tensor5 = torch.ones_like(ten,dtype=torch.int32)
print(tensor4)
print(tensor5)

tensor([[0.4992, 0.5112, 0.2471, 0.4698],
        [0.6694, 0.0674, 0.2358, 0.3076],
        [0.1719, 0.1660, 0.2740, 0.3885]], dtype=torch.float64)
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


to move a tensor from cpu to accelerators we use the following 

In [ ]:
import torch
if torch.cuda.is_available():
    device=torch.device("cuda")
else:
    device=torch.device("cpu")
print(device)


cpu
